repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.1.0
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/python/black
  rev: 19.10b0
  hooks:
  - id: black
    language_version: python3
    args: [--target-version=py36]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    additional_dependencies: ['flake8-bugbear==20.1.4']
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.770
  hooks:
  - id: mypy
- repo: https://github.com/asottile/blacken-docs
  rev: v1.6.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==19.10b0]
